version: '3.9'

networks:
  jpa-network:
    name: jpa
    #external: true

services:
  jpa-db:
    container_name: jpa-db
    image: postgres:16.2
    hostname: learn-jpa
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    networks:
      - jpa-network
    environment:
      POSTGRES_DB: jpa-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "America/Fortaleza"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 30s
      retries: 10