networks:
  movies-network:
    name: movies
  
services:
  movies-db:
    image: postgres:17.0
    hostname: movies-postgres
    ports:
      - 5432:5432
    volumes:
      - movies_db_volume:/var/lib/postgresql/data
    networks:
      - movies-network
    environment:
      POSTGRES_DB: movies-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "America/Fortaleza"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d movies-db -U postgres"]
      interval: 10s
      timeout: 30s
      retries: 10

volumes:
  movies_db_volume: