# - name: GitHub Spellcheck Action
#   # You may pin to the exact commit or the version.
#   # uses: rojopolis/spellcheck-github-actions@dbd2f1da869c05ad874fffeb6fe1ed50cd1a6e98
#   uses: rojopolis/spellcheck-github-actions@0.36.0
#   with:
#     # Alternate configuration file to use
#     config_path: # optional
#     # A list of source files or patterns to scan.
# This overrides your config file's `source` section.
# `task_name` must also be specified to use this option.

#     source_files: # optional
#     # Name of the PySpelling task to run
#     task_name: # optional
#     # Name of a generated output file containing output from pyspelling.

#     output_file: # optional
          
